---
apiVersion: v1
kind: Service
metadata:
  name: registry-lb
  namespace: registry
  labels:
    loadbalancer.home.enabled: "true"
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.2.151
  ports:
    - name: http
      port: 5000
      protocol: TCP
      targetPort: 5000
  selector:
    app: docker-registry
    release: registry
