replicaCount: 2

persistence:
  enabled: true
  accessMode: ReadWriteMany
  size: 20Gi
  storageClass: longhorn-rwx

service:
  port: 5000
  type: ClusterIP

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 1Gi

affinity:
  podAntiAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        podAffinityTerm:
          labelSelector:
            matchLabels:
              app: docker-registry
          topologyKey: kubernetes.io/hostname
