apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ${APP_NAME}-data
  namespace: ${APP_NAMESPACE}
  labels:
    app.kubernetes.io/name: ${APP_NAME}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ${APP_STORAGE_CLASS}
  resources:
    requests:
      storage: ${APP_STORAGE_SIZE}
