apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-porkbun
spec:
  acme:
    email: admin@flowernode.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-porkbun-account-key
    solvers:
      - dns01:
          webhook:
            groupName: acme.flowernode.com
            solverName: porkbun
            config:
              apiKeySecretRef:
                name: porkbun-api-secret
                key: api-key
              secretKeySecretRef:
                name: porkbun-api-secret
                key: secret-key
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: flowernode-com
  namespace: cert-manager
spec:
  secretName: flowernode-com-tls
  issuerRef:
    name: letsencrypt-porkbun
    kind: ClusterIssuer
  dnsNames:
    - flowernode.com
    - "*.flowernode.com"
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: lexih-dev
  namespace: cert-manager
spec:
  secretName: lexih-dev-tls
  issuerRef:
    name: letsencrypt-porkbun
    kind: ClusterIssuer
  dnsNames:
    - lexih.dev
    - "*.lexih.dev"
