---
apiVersion: v1
kind: Service
metadata:
  name: octelium-gateway-udp
  namespace: octelium
  labels:
    app: octelium
    loadbalancer.home.enabled: "true"
    octelium.com/component: gwagent
    octelium.com/component-type: cluster
  annotations:
    io.cilium/lb-ipam-sharing-key: "apisix-gateway"
    kube-vip.io/allow-shared-ip: "apisix-gateway"
spec:
  type: LoadBalancer
  externalTrafficPolicy: Cluster
  loadBalancerIP: 192.168.2.150
  selector:
    app: octelium
    octelium.com/component: gwagent
    octelium.com/component-type: cluster
  ports:
    - name: wireguard
      port: 53820
      targetPort: 53820
      protocol: UDP
    - name: quicv0
      port: 8443
      targetPort: 8443
      protocol: UDP
