arch: amd64
cores: 5
features: nesting=1,keyctl=1
hostname: teddysmp
memory: 14336
net0: name=ens18,bridge=vmbr1,gw=192.168.2.1,hwaddr=BC:24:11:AD:5D:35,ip=192.168.2.100/24,type=veth
ostype: nixos
rootfs: local:100/vm-100-disk-0.raw,size=164G
swap: 1024
lxc.apparmor.profile: unconfined
lxc.prlimit.memlock: unlimited
lxc.mount.entry: /sys/fs/bpf sys/fs/bpf none bind,create=dir
lxc.cgroup2.devices.allow: c 1:11 rwm
lxc.mount.entry: /dev/kmsg dev/kmsg none bind,create=file
lxc.cgroup2.devices.allow: c 10:200 rwm
lxc.mount.entry: /dev/net/tun dev/net/tun none bind,create=file
lxc.mount.auto: proc:rw sys:rw
lxc.cap.drop:
