name: Check

on:
  pull_request:
  push:

permissions:
  contents: read

jobs:
  flake:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v31
      - run: nix flake check --show-trace
